### ISSUE TITLE
Kof94 Graphics Glitches All Over The Place

### ISSUE THREAD

**Issue by mikey1964** [MiSTer-devel/NeoGeo_MiSTer#110]
just play the game and you can see parts of the animation appear in different parts of the screen you can really  see it happen the most in the Korean team stage were you fight Kim

**Comment by Dubon77** [comment]
Could you take some screengrabs of this? Ive tried to reproduce it but havent noticed anything. 
It would also be usefull to specify what rom youre using.

**Comment by mikey1964** [comment]
i tried both the darksoft rom set and the world neo set . my ram passes all test only the neogeo core do i see this and some other games like pulstar but kof 94 is the worst for me the more you move and do combos the more the glitches appear all over the place.  https://gofile.io/d/nCPdQn download video files

**Comment by Dubon77** [comment]
Yeah i dont get those. What ram module do you have and have you run the memtest? I think in some cases reseating the ram has helped.

**Comment by mikey1964** [comment]
yes i ran the memtest and i got the 128

**Comment by Dubon77** [comment]
What speed did it pass consistenly? Have ou tried reseating it?

**Comment by mikey1964** [comment]
> What speed did it pass consistenly? Have ou tried reseating it?

it stays stable at 140 with no errors i have no problems with any other cores its just kof 94  and some other neogeo games the glitches happen so fast you have to have good eyes to catch them

**Comment by Dubon77** [comment]
Did these glitches get introduced since the 28 september build or were you experiencing them with previous builds aswell?
Would you be willing to delete it and download the latest manually?

**Comment by mikey1964** [comment]
> Did these glitches get introduced since the 28 september build or were you experiencing them with previous builds aswell?
> Would you be willing to delete it and download the latest manually?

which one you want me to install  i have the last update of the core i dont rember when the glitches begin

**Comment by Dubon77** [comment]
There was an update on the 28th, the day you submitted this error.
So its worth deleting that build and trying the build before for this error. Its also worth redownloading the latest build, ive had it happen that redownloading a core fixed issues.
Im positive i cant see the glitches on my mister witch also has 128MB sdram. Ive also asked others on discord.

**Comment by mikey1964** [comment]
> There was an update on the 28th, the day you submitted this error.
> So its worth deleting that build and trying the build before for this error. Its also worth redownloading the latest build, ive had it happen that redownloading a core fixed issues.
> Im positive i cant see the glitches on my mister witch also has 128MB sdram. Ive also asked others on discord.

went with NeoGeo_20191014.rbf   i see no glitches and the also i see no text flicker either

**Comment by Dubon77** [comment]
Ok can you redownload the latest build?

**Comment by mikey1964** [comment]
> Ok can you redownload the latest build?

yes i did same bugs it made no diffrence

**Comment by Dubon77** [comment]
Ok well the only thing left to do is try all the older builds untill you find out where the bug was introduced. The is some variance in de10 nano hardware, there are some bugs in Other cores where only some users were affected, witch got fixed over time,  so maybe this is similar. if you can show tell them in witch version of the core the problem started maybe it can be fixed

**Comment by Dubon77** [comment]
Right, well after playing the korea stage multiple times i think i noticed this bug too. As you said you have to be real fast to notice it. This 100% doesnt happen on real hardware right?

**Comment by mikey1964** [comment]
> Right, well after playing the korea stage multiple times i think i noticed this bug too. As you said you have to be real fast to notice it. This 100% doesnt happen on real hardware right?

i never seen it happen in real hardware dont have one to check 
Oct 14, 2019
Release 20191014. - no bugs and letters do not flicker
Nov 13, 2019
Release 20191113. - i get the bugs you see on the videos doesnt seem as bad but they are there also the letters flicker like in issues "KOF 94 Japanese flickering text #73" maybe same problem

**Comment by Dubon77** [comment]
To be honnest if this bug is a regression after oktober 2019 then a bunch of other bugs in #65 might also be regression, particulary everything related to sprite errors and flickering in that list might all have been introduced after that build and if confirmed it would be very valuable info. I’ll try to go through the list tomorrow when im sober.

**Comment by tutifrutas** [comment]
> 
> 
> > Right, well after playing the korea stage multiple times i think i noticed this bug too. As you said you have to be real fast to notice it. This 100% doesnt happen on real hardware right?
> 
> i never seen it happen in real hardware dont have one to check
> Oct 14, 2019
> Release 20191014. - no bugs and letters do not flicker
> Nov 13, 2019
> Release 20191113. - i get the bugs you see on the videos doesnt seem as bad also the letters flicker like in issues "KOF 94 Japanese flickering text #73" maybe same problem

I tracked it down to this commit https://github.com/MiSTer-devel/NeoGeo_MiSTer/commit/b4f924d1f8652a6a3ea5c157edca8c4371f1560a if  I get latest from master, revert this commit and build the core the flickering is gone.

**Comment by mikey1964** [comment]
so far the text flicker and the animations appearing in different parts of the screen are gone

**Comment by sorgelig** [comment]
That commit cannot be reverted as it's important SDRAM timing fix. Probably needs some fixes in other places to accomodate additional clock cycle. 
I will try to fix it.

**Comment by PepAlacant** [comment]
The real cartridge doesn't do that. The NEOSD ( randomly, depends on reset the machine ) and Bootleg carts do.

**Comment by sorgelig** [comment]
try this build:
[NeoGeo.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/7117562/NeoGeo.zip)

**Comment by PepAlacant** [comment]
This one works good KOF 94. This build has not the fixes that GreyRogue did for a layer missplacement in Breakers Revenge, Kabuki Klash, and Kof 2002.

**Comment by Dubon77** [comment]
That build by greyrogue was only a testbuild released on discord. Those fixes were only a hack implemented to track down the underlying issue, so were not comitted to neogeo repo.

**Comment by PepAlacant** [comment]
Ah ok ok ! I understand. Anyway... Kof 94 is fixed. No more flying graphics and no more texts issues.

**Comment by sorgelig** [comment]
great!

**Comment by mikey1964** [comment]
yes its fix after playing for about 2 hours no more text flicker and the animations appearing in different parts of the screen are fix now

**Comment by tutifrutas** [comment]
> try this build:
> [NeoGeo.zip](https://github.com/MiSTer-devel/NeoGelookso_MiSTer/files/7117562/NeoGeo.zip)



> try this build:
> [NeoGeo.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/7117562/NeoGeo.zip)

Thanks, it's works, in kof94 all the text flicker and graphic glitches are gone.

**Comment by mikey1964** [comment]
after the update this issue is back and NeoGeo_MiSTer/issues/73

**Comment by mikey1964** [comment]
hi sorgelig the update cause this issue to come back again

**Comment by sorgelig** [comment]
It means core has metastability issue which can be fixed only after major re-write to comply with FPGA rules.
It can be temporarily "fixed" by trying other SEED values for compilation. But any newer build may bring issue back...

**Comment by PepAlacant** [comment]
Maybe would be good to try to fix the new releases by now... but sadly I have no hope about the future rewrite, but who knows ...

**Comment by PepAlacant** [comment]
The issue is back. It affects only the MVS/AES version, not the CD Version. I think Gyurco did a rework of the core clocks for MiST conversion, I don't know if it could be helpful for definetively fix the MiSTer Core. 

Thanks !
